In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    'x1':[1, np.nan, 3, 4, np.nan, np.nan, np.nan, 11, 12, 13],
    'y1':[1, 2, 3, 4, np.nan, np.nan, np.nan, 8, 9, 10],
    'x2':[1, 2, 3, 4, 5, np.nan, np.nan, 8, 9, 10],
    'y2':[np.nan, 2, 3, 4, 5, 6, np.nan, 8, 9, 10],
}

In [5]:
df = pd.DataFrame(data)

In [7]:
df.head(10)

     x1    y1    x2    y2
0   1.0   1.0   1.0   NaN
1   NaN   2.0   2.0   2.0
2   3.0   3.0   3.0   3.0
3   4.0   4.0   4.0   4.0
4   NaN   NaN   5.0   5.0
5   NaN   NaN   NaN   6.0
6   NaN   NaN   NaN   NaN
7  11.0   8.0   8.0   8.0
8  12.0   9.0   9.0   9.0
9  13.0  10.0  10.0  10.0

In [8]:
df.interpolate()

      x1    y1    x2    y2
0   1.00   1.0   1.0   NaN
1   2.00   2.0   2.0   2.0
2   3.00   3.0   3.0   3.0
3   4.00   4.0   4.0   4.0
4   5.75   5.0   5.0   5.0
5   7.50   6.0   6.0   6.0
6   9.25   7.0   7.0   7.0
7  11.00   8.0   8.0   8.0
8  12.00   9.0   9.0   9.0
9  13.00  10.0  10.0  10.0